# GET request to retrieve the list of users
GET http://127.0.0.1:8000/users/
Accept: application/json
Authorization: Token <your_auth_token>  # if authentication is required

###

# POST request to create a new user
POST http://127.0.0.1:8000/users/
Content-Type: application/json

{
    "username": "newuser",
    "email": "newuser@example.com",
    "password": "yourpassword"
}

###

# GET request to retrieve a specific user by ID
GET http://127.0.0.1:8000/users/1/
Accept: application/json

###

# DELETE request to delete a user by ID
DELETE http://127.0.0.1:8000/users/1/
Accept: application/json
